config/routes.rb
Rails.application.routes.draw do
  resources :users

   root 'users#index'

   match 'users/wizard' => 'users#wizard' , via: [:post, :patch]
   match 'users/wipe_session' => 'users#wipe_session' , via: [:post], as: :wipe_session

end

app/models/user.rb
class User < ActiveRecord::Base

	STEP_REQUIRED_FIELDS = {1=>['username','password'], 2=>['first_name','last_name'], 3=>[]}

	
	def valid_user(step_num)

		valid_user = true
		user_errors = {}

		STEP_REQUIRED_FIELDS[step_num].each do |f|
			if(self.send(f).blank?)
				valid_user = false
				user_errors[f] = "is required"
			end
		end

		return valid_user, user_errors

	end

	def return_step_num
		if(self.username.blank?)
			return 1
		elsif(self.first_name.blank?)
			return 2
		else
			return 3
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    
    @user = nil
    @step_num = 1

    if(session[:user_id].nil?)
      @user = User.new
    else
      @user = User.find(session[:user_id])
      @step_num = @user.return_step_num
    end

    
  end

  # GET /users/1/edit
  def edit
  end

  def wizard
    @user = nil
    valid_user = true
    @step_num = 1

    if(session[:user_id].nil?)
      @user = User.new(user_params)
    else
      @user = User.find(session[:user_id])
      @step_num = @user.return_step_num
      @user.attributes = user_params
    end

    valid_user, user_errors = @user.valid_user(@step_num)
    
    if(valid_user)
      @step_num += 1
      @user.save
      session[:user_id] = @user.id
    else
      user_errors.map{ |k,v| @user.errors[k] = v }
    end

    respond_to do |format|
      format.js { render :content_type => 'text/javascript' }
    end
  end

  def wipe_session
    session[:user_id] = nil
    respond_to do |format|
      format.js { render :content_type => 'text/javascript' }
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Obviously</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="margin:0">

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<script type="text/javascript">
    $('body').on('click', '#step_button', function()
    {
      $("#user_wizard").submit();
    });
</script>

<div style="padding:20px">
  <%= form_for(@user, url: {action: "wizard"}, remote: true, html: { method: :post , id: "user_wizard"})  do  |f| %>
    <div id="error_explanation" style="display:none" >
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>

    <div class="new_user_flow_3"  style="padding-bottom:20px;<%= 'display:none' if (@step_num != 3) %> ">
      Congrats! Your account is complete.
    </div>
    

    <div class="new_user_flow_display" style="<%= 'display:none' if (@step_num == 1) %> ">
      <div class="field">
        <%= f.label :username %>: <span id="user_username_display"><%= @user.username %></span>   
      </div>
      <div class="field new_user_flow_3" style="<%= 'display:none' if (@step_num != 3) %> ">
        <%= f.label :first_name %>: <span id="user_first_name_display"><%= @user.first_name %></span>
      </div>
      <div class="field new_user_flow_3" style="<%= 'display:none' if (@step_num != 3) %> ">
        <%= f.label :last_name %>: <span id="user_last_name_display"><%= @user.last_name %></span>
      </div> 
    </div>

    <div class="new_user_flow_1" style="<%= 'display:none' if (@step_num != 1) %> ">
      <div class="field">
        <%= f.label :username %><br>
        <%= f.text_field :username %>
      </div>
      <div class="field">
        <%= f.label :password %><br>
        <%= f.password_field :password %>
      </div>
    </div>

    <div class="new_user_flow_2" style="<%= 'display:none' if (@step_num != 2) %> ">
      <div class="field">
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name %>
      </div>
      <div class="field">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name %>
      </div>
      
    </div>

    
    
    <div class="actions" style="<%= 'display:none' if (@step_num == 3) %> ">
      <input id="step_button" type="button" value="next step" class="step_button" >
    </div>

  <% end %>
</div>

app/views/users/_user_links.html.erb
<%= link_to ((session[:user_id]) ? 'Continue your user' : 'New user'), new_user_path %> 
<% if(session[:user_id]) %>
 | <%= link_to 'Start a new user', wipe_session_path, method: :post, remote: true %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div style="height:50px;width:100%;background-color:#f7f7f7;padding:20px">
  <h3>Obviously</h3>
</div>

<div style="width:100%;padding:20px">


  <p id="notice"><%= notice %></p>

  <h1>Listing Users</h1>

  <%= render partial: "user_links" %>

  <br/>
  <br/>

  <table cellpadding="7" cellspacing="0" border="0">
    <thead>
      <tr >
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.username %></td>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br/>
  <br/>

  <%= render partial: "user_links" %>

</div>

<div style="height:50px;width:100%;background-color:#f7f7f7;padding:20px;margin-top:20px;bottom:0;position:absolute;">
  <h3>Obviously</h3>
</div>

app/views/users/new.html.erb
<div style="height:50px;width:100%;background-color:#f7f7f7;padding:20px">
  <h3>Obviously</h3>
</div>

<div style="width:100%;padding:20px">

	<h1 id="page_title"><%= (!session[:user_id].nil?) ? "Continue" : "New" %> User</h1>

	<%= render 'form' %>

	<%= link_to 'Back', users_path %>

</div>


<div style="height:50px;width:100%;background-color:#f7f7f7;padding:20px;margin-top:20px;bottom:0;position:absolute;">
  <h3>Obviously</h3>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/wipe_session.js.erb
document.location = "<%= new_user_path %>";

app/views/users/wizard.js.erb
      
      <% if @user.errors.any? %>
        //alert("error!");
        $("#error_explanation").html("");
        $("#error_explanation").show();
        $("#error_explanation").append("<h2><%= pluralize(@user.errors.count, 'error') %> prohibited this user from being saved:</h2>");
        $("#error_explanation").append("<ul>");
        <% @user.errors.full_messages.each do |message| %>
          $("#error_explanation").append("<li><%= message %></li>");
        <% end %>
        $("#error_explanation").append("</ul>");
        $("#error_explanation").append("</div> ");
      <% else %>
        
        //alert(<%= @step_num %>);
        $("#error_explanation").hide();
        $("#step_num").val(<%= @step_num %>);
        $("#user_id").val(<%= @user.id %>);
        $("#page_title").html("Continue User");

        
        <% [1,2,3].each do |i| %>
          $(".new_user_flow_<%= i.to_s %>").<%= (i == @step_num.to_i) ? "show" : "hide" %>();
        <% end %>

        <% if(@step_num.to_i > 1) %>
          $(".new_user_flow_display").show();
          <% if(@step_num.to_i == 2) %>
            $("#user_username_display").html("<%= @user.username %>");
          <% elsif(@step_num.to_i == 3) %>
            $("#user_first_name_display").html("<%= @user.first_name %>");
            $("#user_last_name_display").html("<%= @user.last_name %>");
            $(".actions").hide();
          <% end %>
        <% end %>

        

      <% end %>